/*
 * Mouse wheel callback counter.
 *
 * This program is useful for comparing the number of callbacks generated by
 * the different freeglut window-system backends for the same wheel gesture.
 */
#include <stdio.h>
#include <stdlib.h>
#include <GL/freeglut.h>

#define MAX_WHEELS 4

typedef struct WheelCount
{
    unsigned long callbacks;
    unsigned long positive;
    unsigned long negative;
    long          net;
} WheelCount;

static WheelCount wheels[MAX_WHEELS];
static unsigned long total_callbacks;
static unsigned long other_wheels;
static int last_wheel;
static int last_direction;
static int last_x;
static int last_y;
static int have_last;
static int window_width = 640;
static int window_height = 300;

static void drawString(int x, int y, const char *string)
{
    glRasterPos2i(x, y);
    glutBitmapString(GLUT_BITMAP_9_BY_15, (const unsigned char *)string);
}

static void display(void)
{
    char line[160];
    int wheel;
    int y = 35;

    glClear(GL_COLOR_BUFFER_BIT);
    glColor3f(0.9f, 0.9f, 0.9f);

    drawString(20, y, "Mouse wheel callback counter");
    y += 30;

    sprintf(line, "Total callbacks: %lu", total_callbacks);
    drawString(20, y, line);
    y += 25;

    for (wheel = 0; wheel < MAX_WHEELS; ++wheel)
    {
        sprintf(line,
                "Wheel %d: %lu callbacks  +1: %lu  -1: %lu  net: %ld",
                wheel, wheels[wheel].callbacks, wheels[wheel].positive,
                wheels[wheel].negative, wheels[wheel].net);
        drawString(20, y, line);
        y += 22;
    }

    if (other_wheels)
    {
        sprintf(line, "Callbacks for wheel numbers >= %d: %lu",
                MAX_WHEELS, other_wheels);
        drawString(20, y, line);
        y += 22;
    }

    if (have_last)
        sprintf(line, "Last callback: wheel %d, direction %+d, x %d, y %d",
                last_wheel, last_direction, last_x, last_y);
    else
        sprintf(line, "Last callback: none");
    drawString(20, y, line);

    drawString(20, window_height - 20,
               "Scroll to count callbacks.  R resets; Esc or Q quits.");
    glutSwapBuffers();
}

static void reshape(int width, int height)
{
    window_width = width;
    window_height = height;

    glViewport(0, 0, width, height);
    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    glOrtho(0, width, height, 0, -1, 1);
    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();
}

static void mouseWheel(int wheel, int direction, int x, int y)
{
    ++total_callbacks;

    if (wheel >= 0 && wheel < MAX_WHEELS)
    {
        WheelCount *count = &wheels[wheel];

        ++count->callbacks;
        count->net += direction;
        if (direction > 0)
            ++count->positive;
        else if (direction < 0)
            ++count->negative;
    }
    else
        ++other_wheels;

    last_wheel = wheel;
    last_direction = direction;
    last_x = x;
    last_y = y;
    have_last = 1;
    glutPostRedisplay();
}

static void resetCounts(void)
{
    int wheel;

    for (wheel = 0; wheel < MAX_WHEELS; ++wheel)
    {
        wheels[wheel].callbacks = 0;
        wheels[wheel].positive = 0;
        wheels[wheel].negative = 0;
        wheels[wheel].net = 0;
    }
    total_callbacks = 0;
    other_wheels = 0;
    have_last = 0;
    glutPostRedisplay();
}

static void keyboard(unsigned char key, int x, int y)
{
    (void)x;
    (void)y;

    switch (key)
    {
    case 'r':
    case 'R':
        resetCounts();
        break;
    case 'q':
    case 'Q':
    case 27:
        glutLeaveMainLoop();
        break;
    }
}

int main(int argc, char **argv)
{
    glutInit(&argc, argv);
    glutInitDisplayMode(GLUT_RGB | GLUT_DOUBLE);
    glutInitWindowSize(window_width, window_height);
    glutCreateWindow("freeglut mouse wheel counter");

    glClearColor(0.08f, 0.09f, 0.12f, 1.0f);
    glutDisplayFunc(display);
    glutReshapeFunc(reshape);
    glutKeyboardFunc(keyboard);
    glutMouseWheelFunc(mouseWheel);
    glutMainLoop();
    return EXIT_SUCCESS;
}
